spring:
  profiles:
    active: local
  application:
    name: test-server-spring

server:
  port: ${SERVER_PORT}
  servlet:
    context-path: /api/test-server-spring
    encoding:
      charset: utf-8
      enabled: true
      force: true

springdoc:
  swagger-ui:
    enabled: true
    csrf:
      enabled: true