name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
  release:
    types: [published]

jobs:
  bootjar-build:
    name: Gradle Build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle*', '**/settings.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set version from Git tag
        run: echo "GITHUB_REF=${GITHUB_REF}"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@dbbdc275be76ac10734476cc723d82dfe7ec6eda # v3.4.2
        with:
          gradle-version: 8.5

      - name: Build Spring Boot application with Gradle
        run: ./gradlew clean bootJar --info --stacktrace
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_TAG: ${{ github.ref_name }}

      - name: List build/libs contents
        run: ls -la build/libs/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: built-jar-artifacts
          path: build/libs/*.jar
          compression-level: 9 # maximum compression

  build-and-publish-docker-hub:
    name: Build and Publish Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs: bootjar-build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: built-jar-artifacts
          path: build/libs/

      - name: Display structure of downloaded files
        run: ls -R build/libs/

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get Git commit SHA for versioning
        id: vars
        run: |
          echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image (develop)
        if: "${{ github.ref_name == 'develop' }}"
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg VERSION=${{ github.ref_name }} \
            --tag aikusoni/ats-test-server-spring:develop \
            --push .

      - name: Build and Push Docker image (release)
        if: "${{ github.event_name == 'release' }}"
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg VERSION=${{ github.ref_name }} \
            --tag aikusoni/ats-test-server-spring:${{ github.ref_name }} \
            --tag aikusoni/ats-test-server-spring:latest \
            --push .